---
title: "ConnectDatabase.Rmd"
output:
  html_document: default
  pdf_document: default
date: "2024-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)


reviews <- data.frame()

link <- "https://www.imdb.com/title/tt0068646/reviews/?ref_=tt_ql_2"
session <- bow(link, user_agent = "Educational Purpose")

movie <- function(selector) {
  scrape(session) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
}

title <- movie("a.subnav_heading")
reviewername <- movie("span.display-name-link")[1:10]
date <- movie("span.review-date")[1:10]
rating <- movie("span.rating-other-user-rating")[1:10]
review <- movie("div.text.show-more__control")[1:10]
title_Review <- movie("a.title")[1:10]

reviews <- rbind(reviews, data.frame(
  title = rep(title, 10),
  reviewer = reviewername,
  date = date,
  rating = rating,
  text = review,
  title = title_Review
))

reviews

```

```{r}
library(dplyr)
library(RMariaDB)
library(RMySQL)

connection <- dbConnect(RMySQL::MySQL(), 
                        dsn="MySQL-connection",
                        Server = "localhost",
                        dbname = "ReviewsData", 
                        user = "root", 
                        password = "")  

dbListTables(connection)
dbListFields(connection,"moviesdata")


```

```{r}
data <- dbGetQuery(connection, "SELECT * FROM ReviewsData.moviesdata")

glimpse(data)
```

### INSERT INTO DATABASE

FIRST REVIEW 
```{r}
DBQuery <- " INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','CalRhys','20 June 2014','10/10', 'The Godfather is the pinnacle of flawless films! The first time I viewed The Godfather I was in my early teens and it was the most astounding film I had ever seen, and has since then stood as my all-time favourite film. It is due to this that I have been looking forward to writing a review of this unforgettable classic. So lets start from the beginning. The film opens to four words, I believe in America, its crazy to think that this simple line has become a resonant quote solely due to the impact it made on the entrance to the films threshold. This is just one of the many renowned quotes that litter the film, and believe me, there are a lot. After the first take we are then absorbed into the life of Vito Corleone, brilliantly portrayed by the Oscar- winning performance of Marlon Brando. Vito is a feared man, he is a criminal, he is a mafioso, but above all he is a respected family man, his three sons are depicted by three excellent actors, James Caan, John Cazale and Al Pacino as well as his adopted child Tom Hagen, played by Robert Duvall. The film follows Vito as he attempts to transfer his crime empire to his reluctant son, Michael. With some of the most graphic and gruesome death scenes to have ever been seen in the 1970s film industry (including a certain horses head), The Godfather epitomises how violence can be used effectively within a film. The Corleones are some of the greatest antiheroes to have ever been seen on screen, whilst they are villains, the audience will refuse to accept that fact, Coppola does something simple and audacious, he takes the guilt out of organised crime. A film rife with beautiful cinematography, memorable musical scores and well-paced action and drama. Overall, The Godfather is one of Hollywoods greatest critical and commercial successes that gets everything right a gangster flick that is overflowing with life, rich with emotion and subtle acting, and further blessed with amazing direction from Francis Ford Coppola. Arguably the most unforgettable masterpiece to have ever been made.', 'The Pinnacle Of Flawless Films!' )"


DBresult <- dbSendQuery(connection, DBQuery)


dbClearResult(DBresult)
```

SECOND
```{r}
DBQuery <- " INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','andrewburgereviews','1 April 2019','10/10', 'It is now past 1 PM and I just finished watching Francis Ford Coppolas The Godfather. I should probably go to bed. Its late and tomorrow I have to wake up a bit early. But not early enough to postpone writing these lines. Now that I have seen it three times, the opportunity of sharing my thoughts and refreshed insights are too much of a good offer to sit on. So, bear with me.This film works so well because it takes place in an underworld in which we are so embedded that we do not even observe it. Coppola puts us straight in the smack-dab center of what is, admittedly, a society made by criminals for criminals. It is also the reason why its so welcoming. We are surrounded by its inhabitants--cold-blooded murderers, men who see crime like a 9 to 5 job masquerading as honorable men. And I do mean men. From the outside, we would only witness the horrifying, disturbing manifestations of their well-thought out actions.But it goes even deeper than that. It all revolves around the Corleone family led by Don Vito Corleone (Marlon Brando). He is the most honest of these men, sitting right on the edge. But for people like him, who do not fully embrace this world, its not easy. He avoids conflict until it is absolutely necessary. He is a man defined by moral principles. There is a scene at the beginning, in which, during his daughters wedding day, one of his associates, Luca Brasi (Lenny Montana) practices his speech that he is going to give to the Don when he meets him. The scene with these two is funny and almost adorable. I could not help but sympathize both of them only to realize that I am feeling warmth for two mobsters. Not to even mention that Lenny Montana was an actual mob hit-man and that he was actually nervous as he said that line.The more I watched the more I realized just how incredibly complex and ruthless this society is and how it has the power to corrupt anyone to come in contact with it. The best example is Corleones youngest son, Michael (Al Pacino). He returns home for his sisters wedding as a war hero dressed the part with his long-time girlfriend, Kay Adams (Diane Keaton). At first, he avoids this underworld, but necessity, first hand exposure and just its sheer devilish appealing nature draws him in. As we get further in the film, the change is shocking and every outsider who ever got close to him is tainted in one way or another. If they survive it, they are drawn in as well as we are as viewers.Inside, Coppola exposes the family to us fully, with a bold personal approach and we witness every discussion, every methodically calculated choice. Crime is done simply because it is the nature of their business, and we are put on a chair alongside them, so we easily relate. For us, they are the good guys, the rival families are the bad guys. This is the greatest feat this film managed to pull off--set apart good guys and bad guys in a world filled with bad guys.This is a film of unmatched subtlety. No other movie sustains itself as good. No other film is done with such precision, attention and completeness. There are many layers which I probably missed and maybe will never notice. But I felt them. What director Francis Ford Coppola and his partner in crime (poor choice of words, sorry) Mario Puzo did is nothing short of a timeless piece of reference cinema whose influence is not based on reinventing the wheel, but rather perfecting it to the absolute maximum.Most masterpieces are remembered for their historical contributions. Citizen Kane brought the biggest step-up to the art form, the same things did Gone With the Wind or 2001: A Space Odyssey.The Godfather is one of the few films that will be remembered simply because they are that good and I cannot possibly imagine a greater achievement.', 'The Pinnacle Of Flawless Films!' )"



DBresult <- dbSendQuery(connection, DBQuery)


dbClearResult(DBresult)
```

THIRD REVIEW
```{r}

DBQuery <- " INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','Sleepin_Dragon','6 February 2021','10/10','A masterclass in film making, is The Godfather a contender for the best film of all time? Id argue the case that it is, this is the ultimate gangster movie.Before you panic at the thought of a film being almost three hours long, you neednt, you wont even notice the time, it flies by.Production values are incredible, it looks sublime the whole way through, its so well produced, at roughly fifty years old it puts many new films to shame.Brandon, Pacino and Castellano, just a few of the Incredible performances, I could add a whole lot more.If youre considering buying a hard copy, I would recommend it on blu ray, it is sharper than the dvd, there is a difference.This film has had a huge influence down the years, it is still, and will forever be, one of the greatest, 10/10.','One of the best of all time.')"

DBresult <- dbSendQuery(connection, DBQuery)

dbClearResult(DBresult)
```


FOURTH REVIEW 
```{r} 

DBQuery <- " INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','gogoschka-1','11 February 2018','10/10','This isnt just a beautifully crafted gangster film. Or an outstanding family portrait, for that matter. An amazing period piece. A character study. A lesson in filmmaking and an inspiration to generations of actors, directors, screenwriters and producers. For me, this is more: this is the definitive film. 10 stars out of 10.Favorite films: IMDb.com/list/mkjOKvqlSBs/Lesser-Known Masterpieces: imdb.com/list/ls070242495/','For Me, This Is The Definitive Film')"

# Execute 
DBresult <- dbSendQuery(connection, DBQuery)

# clear the result 
dbClearResult(DBresult)

```

FIFTH REVIEW 
```{r}
 
  DBQuery <- " INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','0U','23 February 2020','10/10','One of the best films of all time, an absolute masterpiece. The Godfather is arguably the best gangster drama as well as setting the standard for cinema.','The greatest movie of all time!')"


  DBresult <- dbSendQuery(connection, DBQuery)

  
  dbClearResult(DBresult)

```

SIXTH REVIEW 
```{r}
DBQuery <- " INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','alexkolokotronis','21 June 2008','10/10','Tell me a movie that is more famous than this. Tell me a movie that has had more parodies spinned off its storyline than this. Tell me one movie that has been as quoted as a much as this. The answer is you cant. No movie has had as much of an impact as The Godfather has had ever since it was released.The acting was simply amazing, what else could you say. What could be more appealing to people(even today) than watching actors like Al Pacino, Marlon Brando, James Caan, Diane Keaton, Talia Shire and Robert Duvall. This is like heaven for someone who is a fan of movies. With this movie Brando was able to bring himself back into the limelight. His performance as the godfather alone is iconic. His character has been recreated so much in films that it has almost if it has not already become a cliché. His performance though was not a cliché. His performance was subtle and breathtaking. It was so genuine and realistic that it was not just probably but definitely more genuine than Marlon Brando himself. Al Pacino was perfect for this film as well. What a way to start up your career. His character was all about depth and he displayed it perfectly. He was able to display his own inner-battles in his mind as well as the battles he had with his family, friends and enemies. His character was more of a psychological character study than anything else to me. Robert Duvall to me was the glue to the movie. He added a different perspective to everything in just that he was not Italian yet having the respect of the mafia. His character is a man of high authority within the Corleone family who was listened to and insightful;. This was simply perfect giving the film great balance throughout. The rest of the cast was just icing on the cake.The writing was phenomenal and breathtaking. As mentioned before there has been no movie quoted more than this. It is not even the quotes though that makes the writing in here so perfect. It is the symbolism and meaning that went into every scene. There are countless symbols, messages and lines in here that are so memorable yet it is as realistic as a movie could get.The directing by Coppola was perfect as well. Not many movies can be 3 hours and yet maintain a good level of interest from the audience like The Godfather. Coppola deserves credit for this. The symbolism and messages that went into every scene also has to do with the directing not just the writing. The movie is so well edited and strung together that the only word that could come to my mind is perfection.The cinematography and music were perfect. The score of this movie is one of the most memorable ever. If you were to hear it you could identify it right away. The cinematography was what actually really drove this movie. The Godfather seems to have this mystique to it, it gives you the feeling you are watching something truly remarkable.The horses head, the scene of Brando running with his groceries, the coffee shop scene, Ill give him an offer he cant refuse and countless other scenes and quotes from this movie have become a part of our culture. These scenes and lines have been recycled over and over again in comedies, commercials, etc. that it is impossible to avoid the greatness of The Godfather. The Godfather is like a disease once you see it you fall in love with it. I dont know if it is the greatest movie ever but it is definitely the most iconic film ever made.','An Iconic Film')"


  DBresult <- dbSendQuery(connection, DBQuery)

  
  dbClearResult(DBresult)
```

SEVENTH REVIEW 
```{r}

  DBQuery <- "INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','b-a-h TNT-6','5 March 2002','10/10','The Godfather is one of the few films in which I personally did not find any significant weakness even after many viewings. From the direction, to the acting, to the storyline, to the score, The Godfather has the word classic written all over, and it really is not much of a surprise that it is now considered by many one of the top five movies of all time. Perhaps when it comes to cinematic techniques The Godfather has not been as revolutionary as Citizen Kane, but its influence on motion pictures is comparable. Rarely a movie has defined or re-defined a genre as much as this one did for gangster movies, but its influence goes well beyond that.The Godfathers influence has been so big through the years that elements of it can be found in virtually every organized crime film nowadays; almost every comedy featuring a gangster in the last few years has spoofed something in The Godfather. The Italian-American old mobster a-la Don Vito Corleone has become one of the most established figures in the publics imagination.But to say that The Godfather is simply influential is to diminish its true qualities, and so is to describe it simply as a movie about gangsters. The Mafia is certainly the main focus the story revolves around (despite the fact that the word is never mentioned), but although the movie never tries to forcedly insert separate subjects it contains an amount of psychological and social subtexts that cannot be overlooked. Considerations on how the social environments changes us, on how moral values appear different from different point of views, on how violence can destroy a human soul, and on how power can corrupt an individual are deeply blended into a story that stays practically always true to complete realism, and the result is a picture of astonishing efficacy and believability.As good as the direction and the story are, it would be unfair not to consider the major role that the actors performances had in the cinematic triumph that was The Godfather. Praised by many as the best cast to ever appear in an American movie, all the cast in The Godfather succeeds in portraying complex, three-dimensional characters without ever making a slip. The exceptional portrayals of Don Vito and Michael Corleone respectively by Marlon Brando and Al Pacino, the performances by Robert Duvall, James Caan and Diane Keaton as Tom Hagen, Santino Corleone and Kay Adams, the ruthless Virgil Sollozzo played by Al Lettieri -- as well as more than a few other roles -- are all perfect for the movie, and they all succeed in making us believe these are real people, not just actors. We are not watching a central character and a bunch of incomplete figures that revolve around him: although Michael Corleone is the character that gets the most screen time, everybody is the center of this world his own way. The movie makes it possible for the viewers to identify with different characters and to observe how their personality and story fits in, and it does it much more effectively than many bloated multiple-storyline movies that came out in the last few years.The movie opens on the wedding of Don Vito Corleones daughter, Connie (Talia Shire). Don Corleone is a powerful man, and it was not without the use of violence that he achieved this position during the course of his life. The wedding scene gives a perfect setting of where and how the Dons power extends; from the regular worker in a neighborhood, to the immensely popular singer, to the friends in politics and right to the ruthless killer, Don Corleone has links to people ready to ask him favors and to pay him back. Some are trustworthy, some are not, but thanks to his intelligence and intuit the Don can almost always distinguish the two.However, this is 1946, times are changing, and to many of the younger people working in the crime business, Don Corleones ideas are becoming obsolete. The Don believes that the new trend in the business, narcotics, is too dangerous and the families dealing with it would eventually end up self-destroying; while his family had deals in alcohol and gambling for a long time, part of the Government and law enforcement was ready to close one eye. Drugs are another thing.To this day, Don Corleone was able to keep things together while maintaining his economic and political power, but things will brutally change when a powerful drug dealer name Sollozzo enters the picture. The refusal of Don Corleone to cooperate with Sollozzo, and a weakness immediately spotted by the latter, will ignite a war that will cost many lives, and that will see Michael Corleone, Vitos younger son and the one who never wanted to take part in the family business, lose his innocence and transform into a gangster as ruthless as the people he initially stood up against.I purposely decided not to spoil much about the plot because I believe that the film is perfectly enjoyed without knowing anything in advance, and -- believe it or not -- there are still quite a lot of people who have never seen this movie. There are multiple scenes that manage to create an incredible tension, various twists, and although like any other masterpiece The Godfather can be watched knowing the whole story beforehand and still be a phenomenal experience, I believe it is always a pleasure to see it for the first time and enjoy its multiple climaxes. Besides, to outline such complicated characters and such an emotionally intense story in a short review like this one would be inadmissible.There has been much speculation on how the events in The Godfather novel written by Mario Puzo, the book the film is based on, could be an exposé of true facts. Many believe that the character of Johnny Fontane , for instance, was based on Frank Sinatras real life, and many of the other characters were modeled after real people. I wont go into that: frankly, I have no idea whether these voices are reliable, although the Frank Sinatra reference seems obviously quite believable.The cinematography of The Godfather is dark and tasteful, and colors are used perfectly to give a true feel of the era it is set in. There is a fair amount of violence, though rarely gratuitous.The Godfather certainly doesnt need my recommendation. The film is universally considered one of the best of all time, and the performances by Pacino and Brando alone is the stuff of legends.','Another kind of family movie')"


  DBresult <- dbSendQuery(connection, DBQuery)

  
  dbClearResult(DBresult)
```

EIGHTH REVIEW 
```{r}
  DBQuery <- "INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','planktonrules','30 March 2013','10/10','Up until today, I havent bothered to review The Godfather. After all, everyone pretty much knows its one of the greatest films ever made. Its 2 on IMDbs Top 100. It won the Best Picture Oscar. And, there are nearly 1600 reviews on IMDb. So whats one more review?! Well, after completing 14,000 reviews (because I am nuts), I guess its time I got around to reviewing a film I should have reviewed a long time ago. So, here goes....the film is perfect and only a dope wouldnt watch it. Unfortunately, IMDb requires me to say more to meet its 10 line minimum for reviews. So, Ill point out that you do NOT need to like gangster films to enjoy this film. Yes, its violent and nasty in spots--but its also brilliantly written and produced from start to finish and deserves the accolades its received.My advice is that instead of just watching The Godfather and The Godfather: Part II, see the combined version they created for television--with additional scenes that made it a very rich experience.','2 on IMDbs Top 100, a multi-Oscar-winner and over 1500 reviews...what more can I say about the movie?!')"


  DBresult <- dbSendQuery(connection, DBQuery)

  
  dbClearResult(DBresult)
```

NINTH REVIEW 
```{r}
  DBQuery <- " INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','TheLittleSongbird','18 July 2010','10/10','There is very little that I can add to the reviews on here, that have explained what is so wonderful about The Godfather so well. I have seen many amazing movies, as well as some clunkers, but The Godfather was beyond amazing. There are so many images, details and scenes that I seriously cannot get out of my head since watching it for the first time just nine hours ago. The Godfather is so incredibly well-made and acted that it stands out among the rest of those other amazing films Ive seen, so much so I couldnt think of a single flaw, and I am struggling to think of a good enough reason to why I didnt see this film before now.True, The Godfather is a little slow-moving and the plot takes a while to unfold, but neither of these are flaws as such. The slow pacing added to the elegiac quality The Godfather has, and as for the plot what is special about this plot is that it is very unpredictable because you have next to no idea where it is next going to take you. Being 18, I was worried whether I was old enough to appreciate this film or even understand it, but luckily I understood it perfectly, and I can well and truly appreciate it for the masterpiece it is considered to be.The Godfather for one thing looks stunning. I strongly disagree with the previous reviewer who said the cinematography was horrid, for me the cinematography was one of the best assets of the film. In some scenes you have cinematography and lighting that is quite dark and mysterious, and then in scenes such as the wedding it is evergreen, autumnal and very picturesque. It is not just the cinematography that makes The Godfather look stunning, the costumes are beautifully tailored, the houses are gorgeous and majestic to look at and even the cars were immaculate.Then there is the score by Nina Rota. One word, outstanding! I have heard many wonderful scores in my lifetime, but after hearing this score few stick in the memory as much as the score for The Godfather. This score is both beautiful as seen with the main theme, and haunting in the way it sticks in your head after watching the film itself. Other outstanding assets are the masterly direction from Francis Ford Coppola, and the brilliantly written screenplay that is intelligent, thought-provoking and darkly humorous. As for the violence, some of it is shocking and intense especially in the climax which was enough to almost make your heart either beat twice as fast or stop, and I almost covered my eyes when the producer found the horses head in his bed, but underneath that this family is somewhat loyal and honourable come to think of it.The acting is absolutely fantastic, bringing to life characters that are rich and complex, perhaps unlikeable at first but as you get to know them you warm to them. And I have to say, The Godfather is one of those rarities where no actor gives a weak performance. In particular, Marlon Brando is brilliant as Don Vito, very heavily disguised yet stately. Every word of dialogue, every subtle hand gesture and every facial expression was brilliantly judged. Al Pacinos casting was admittedly risky, but he still did a truly wonderful job carrying the film, while James Caan is dignified and loyal, Diane Keaton beautiful and alluring and Robert Duvall nicely understated.In conclusion, absolutely amazing, and I can see completely why it is considered one of the 10 greatest movies ever made, it is that good. In fact my 15-year old brother loved it so much, he wants to see it again. 10/10, though this film is too good for that rating. Bethany Cox','Im finding it hard to describe how amazing this movie was')"


  DBresult <- dbSendQuery(connection, DBQuery)

  
  dbClearResult(DBresult)

```

TENTH REVIEW 
```{r}

 
  DBQuery <- " INSERT INTO moviesdata (movietitle, reviewer, reviewdate, stars, textreview, titlereview ) VALUES ('The Godfather','mattrochman','14 October 2006','10/10','This is a masterpiece. A timeless masterpiece. Initially, I didnt like this film all that much - I found it rather over-hyped and boring. This was until the advent of DVD, which gave me the feature I needed for this sort of film: subtitles. Once I switched them on and heard (read) every last word of Brandos ramblings and other characters ramblings, I grew a true appreciation for this epic.To make a true epic, you need all of three following ingredients working in near perfect harmony. For screenwriters who come across this, take the following pointers on board: 1) Contrasting Characters: Good films have some character distinction, but most fall rather flat because the core of each character is the same.Of course, there are exceptions to rule (ie... where you want mono-tonal characters... aka matrix; or where you want outlandish contrasts... aka The Fifth Element), but ultimately, this is what makes films deep, meaningful and grand. Consider the contrasts between the Dons children. Michael is rather cool, rational and collected, whereas Sonny is more hot-headed, spontaneous and simple minded. But simply having these contrasts is not nearly enough. What you really need to do is to develop these characters - place them in situations - and then dwell on how their character impacts on the situation theyre put in. The Godfather is a terrific example of how to pull this off. While many try to do this in screenplays, most lose the plot and create character obscurities that stretch credibility.2) Transformation: The central character(s) must undergo a transformation, resulting in them being almost unrecognizable by the end of the film. By putting them into situations, the characters character must not only influence the outcome of the situation; it must also have a lasting impact on the character. Consider Michael at the wedding and compare that to the Michael we see at the end of the film. Again, many films try, but most fail because they come up with unreal (literally, not praisingly) or simply moronic transformations (eg, Wall Street).3) Patience: Men in Black 2 was an astounding film for one simple reason - it was an entire film squashed into about 70 minutes. It was not much longer than an episode of ER or Buffy. I certainly hope the new goal of Hollywood isnt to make films as short as possible.All the great ones spend time - time developing characters, family life, growth, patience with the story telling in general. This is the key (provided that the story isnt mind-numbingly boring). Dances with Wolves, Heat.. and so on are very patient but top-class films. While studios may be lukewarm on the idea of longer films, they are worth it if you have a ripper story to base it on.I feel that this film has not dated all that much and has tremendous re-watch-ability.','Initially, I wasnt a fan... but then I realised')"


  DBresult <- dbSendQuery(connection, DBQuery)

  
  dbClearResult(DBresult)


```
```{r}
#read and write data from database
data <- dbGetQuery(connection, "SELECT * FROM ReviewsData.moviesdata")

#export to csv
write.csv(data [(1:10), ], "moviedata.csv")

```

